---
title: "ITSM h5 Overview"
author: "Rajiv Sambasivan"
date: "2023-08-18"
output: 
  cleanrmd::html_document_clean:
    theme: markdown-retro
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Overview of ITSM Data Processing

### Data Exploration
* Identify the attributes in the dataset
* Identify the size of the dataset
* Identify the default types in the dataset
* Assess the missing values for the different attributes in the dataset
* Fix the missing values for each data type. This means that the method or strategy to address missing values depends on the data type. Categorical values are addressed one way, datetime types are addressed in a different way.
* Assign the correct data type for each attribute.
* Create the annotation information to insert into the h5 file.
* The above steps are all the processing that is required to arrive at a version of the dataset that is amenable for further analysis. If this processing is not done, missing values and incorrect datatype assignments will prevent the analysis of this data. These steps give us a processable version of the raw data.
* Write the h5 file.
* See the notebook name ITSM_EDA for details of the implementation.

### Analytics Processing
* Purpose: Develop reports that summarize the ticketing activity for the help desk organization.
* Develop the ticketing data for Q1. This involves the following steps:
    * Select Q1 data by filtering on the date.
    * Group Q1 data by assignment group and aggregate (sum) the tickets for each group
    * Prepare the plotly report.
    * The process of creating a report for Q2 is exactly the same as Q1 with the date ranges changed.
* Write Q1 data to ITSM h5 file.

### Data File Layout
The ITSM dataset has the following structure:
* summary directory: Contains annotation describing the usecase, organization of the directory and specific guidelines useful in understanding the methodology and rationale used to develop the analytics or machine learning model. This document is an example of information belonging to this category.

* raw_dataset directory: Contains the completely processed raw dataset that is used for preparing analytical reports or statistical/machine learning models.

* raw_dataset/raw_table_issues: Contains information about issues discovered in exploratory data analysis that need to be fixed to obtain a dataset that can be used to develop analytical or statistical models

* raw_dataset/raw_table_processing_summary: Contains information about the processed raw dataset **after** cleaning. This is the dataset state at the beginning of analytical or machine learning model development.




