name: jekyll-cd

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    env:
       working-directory: ./docs

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: 🎩 Install Jekyll
        run: |
          sudo gem install bundler jekyll
          sudo bundle install .
      - name: 🔨 Build site
        run: bundle exec jekyll build -d docs
      - name: 🧪 Deploy build
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -am "🧪 Deploy with ${GITHUB_WORKFLOW}"
          git push --all -f https://${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
