on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  upload-site-to-github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/upload-artifact@v3
        with:
          name: 'github-pages'
          path: docs/_site


    
